envs: &vars
  DOTNET_PATH: $CM_BUILD_DIR/dotnet
  DOTNET_BIN: $CM_BUILD_DIR/dotnet/dotnet
  BUNDLE_ID: "io.r3t.retrans"

env-groups: &env-groups
  groups:
    - azure
    - google_credentials

env-android: &android-env
  android_signing:
    - Demo Key
  <<: *env-groups
  vars:
    <<: *vars
    DOTNET_WORKLOAD: "maui"
    TARGET_FRAMEWORK: "net7.0-android"
    IS_ANDROID: "1"

env-ios: &ios-env
  environment:
    android_signing:
      - Demo Key
    <<: *env-groups
    vars:
      <<: *vars
      TARGET_FRAMEWORK: "net7.0-ios"
      IS_IOS: "1"

install-git-lfs: &install-git-lfs
  name: install-git-lfs
  script: |
    git lfs install --skip-smudge

install-dotnet: &install-dotnet
  name: install-dotnet
  script: |
    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 7.0 --quality GA

install-maui: &install-maui
  name: install-maui
  script: |
    $DOTNET_BIN nuget locals all --clear
    $DOTNET_BIN workload install $DOTNET_WORKLOAD

dotnet-restore: &dotnet-restore
  name: dotnet-restore
  script: |
    $DOTNET_BIN restore

# build info generator, must come after build-number
prebuild-script: &prebuild
  name: generate-credentials
  script: |
    ./prebuild.sh

dotnet-build: &dotnet-build
  name: dotnet-build
  script: |
    cd src
    $DOTNET_BIN build --no-restore -f $TARGET_FRAMEWORK

publish-config-google: &google-publish-config
  google_play:
    credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    track: internal
    submit_as_draft: true

build-number: &build-number
  name: generate-build-number
  script: |
    echo "VERSION=$(date +%Y.%m.%d)" >> $CM_ENV

android-package: &android-package
  name: dotnet-package-android
  script: |
    $DOTNET_BIN publish src/retrans.csproj --no-restore -f $TARGET_FRAMEWORK \
      -c Release \
      -p:AndroidKeyStore=True \
      -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
      -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS \
      -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD \
      -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD \
      -p:ApplicationVersion="${BUILD_NUMBER}" \
      -p:ApplicationDisplayVersion="${VERSION}" \
      -o /Users/builder/clone/artifacts

set-plist-values: &set-plist-values
  name: set-plist-values
  script: |
    PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
    PLIST_BUDDY=/usr/libexec/PlistBuddy
    $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

package-ios: &ios-package
  name: dotnet-package-ios
  script: |
    CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name')
    PROFILE_NAME=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -execdir sh -c '/usr/libexec/PlistBuddy -c "print :Name" /dev/stdin <<< $(security cms -D -i {})' \;)

    $DOTNET_BIN publish -f net7.0-ios \
      -c Release \
      -p:BuildIpa=True \
      -p:ApplicationDisplayVersion="1.0.0" \
      -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
      -p:RuntimeIdentifier=ios-arm64 \
      -p:CodesignKey="$CERT_NAME" \
      -p:CodesignProvision="$PROFILE_NAME" \
      -o /Users/builder/clone/artifacts

artifacts-build: &build-artifacts
  artifacts:
    - /Users/builder/clone/artifacts/*Signed.aab
    - /Users/builder/clone/artifacts/*.ipa

when-not-code: &when-not-code
  changeset:
    excludes:
      - "**/*.md"
      - "**/*.txt"

pull-request: &pull-request
  triggering:
    events:
      - pull_request
    branch_patterns:
      - pattern: 'mainline'
        include: true
        source: false


workflows:
  maui-ios:
    name: iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      <<: *env-groups
      vars:
        <<: *vars
    scripts:
      - *install-git-lfs
      - *install-dotnet
      - *install-maui
      - *build-number
      - *prebuild
      - *dotnet-restore
      - *ios-package
    artifacts:
      - ./artifacts/*.ipa
  maui-android:
    name: Android
    <<: *pull-request
    when:
      <<: *when-not-code
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      <<: *android-env
    scripts:
      - *install-git-lfs
      - *install-dotnet
      - *install-maui
      - *build-number
      - *prebuild
      - *dotnet-restore
      - *dotnet-build
      - *android-package
    <<: *build-artifacts
  maui-publish:
    name: Publish
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'mainline'
          include: true
          source: true
    environment:
      <<: *android-env
    scripts:
      - *install-git-lfs
      - *install-dotnet
      - *install-maui
      - *build-number
      - *prebuild
      - *dotnet-restore
      - *android-package
      - *ios-package
    <<: *build-artifacts
    publishing:
      <<: *google-publish-config