install-dotnet: &install-dotnet
  name: install-dotnet
  script: |
    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 7.0
install-maui: &install-maui
  name: install-maui
  script: |
    $DOTNET_BIN nuget locals all --clear
    $DOTNET_BIN workload install $DOTNET_WORKLOAD
envs: &vars
  DOTNET_PATH: $CM_BUILD_DIR/dotnet
  DOTNET_BIN: $CM_BUILD_DIR/dotnet/dotnet
  BUNDLE_ID: "io.r3t.retrans"

workflows:
  maui-ios:
    name: iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
#    integrations:
#      app_store_connect: api-access-codemagic
    environment:
#      ios_signing:
#        distribution_type: app_store
#        bundle_identifier: io.codemagic.maui.weather
      vars:
        <<: *vars
        DOTNET_WORKLOAD: "ios maui"
#        APP_ID: 6444530615
#        BUNDLE_ID: "io.codemagic.maui.weather"
    scripts:
      - *install-dotnet
      - *install-maui     
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
      - name: Set build version and build the app
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
          if [ -z $LATEST_BUILD_NUMBER ]; then
             UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
             UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          
          buildNum="$(date +%Y.%m).${UPDATED_BUILD_NUMBER}"
          
          CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name')
          PROFILE_NAME=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -execdir sh -c '/usr/libexec/PlistBuddy -c "print :Name" /dev/stdin <<< $(security cms -D -i {})' \;)
          
          $DOTNET_BIN publish -f net7.0-ios \
            -c Release \
            -p:BuildIpa=True \
            -p:ApplicationDisplayVersion="1.0.0" \
            -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignKey="$CERT_NAME" \
            -p:CodesignProvision="$PROFILE_NAME" \
            -o ../artifacts
    artifacts:
      - ./artifacts/*.ipa
#    publishing:
#      app_store_connect:
#        auth: integration
  maui-android:
    name: Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - Demo Key
      groups:
        - google_credentials
      vars:
        <<: *vars
        DOTNET_WORKLOAD: "android maui wasm-tools"
    scripts:
      - *install-dotnet
      - *install-maui      
      - name: Build
        script: |
          LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_BUILD_NUMBER ]; then
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          
          buildNum="$(date +%Y.%m).${UPDATED_BUILD_NUMBER}"
          
          $DOTNET_BIN publish -f net7.0-android \
            -c Release \
            -p:AndroidKeyStore=True \
            -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
            -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS \
            -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD \
            -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD \
            -p:ApplicationVersion="${buildNum}" \
            -p:ApplicationDisplayVersion="${buildNum}" \
            -o ../artifacts
    artifacts:
      - /Users/builder/clone/artifacts/*Signed.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true